# This conda environment supports pygetm installation on Read the Docs servers
name: pygetm
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - cmake
  - ninja  
  - gfortran
  - cython
  - python-build
  - pip
  - mpi4py
  - mpich
  - numpy
  - xarray
  - netcdf4
  - scipy
  - pyfabm>=2.1
  - awex
  - pygotm
  - sphinx_rtd_theme>=2.0
  - rioxarray
